### ISSUE TITLE
mongoose problem

### ISSUE THREAD

**Issue by Loupning** [rm2kdev/Mmorpg-Server#1]
Initialize Completed, Server runnng on port: 8082 for environment: test
(node:2512) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise
library instead: http://mongoosejs.com/docs/promises.html

events.js:160
      throw er; // Unhandled 'error' event
      ^
MongoError: failed to connect to server [127.0.0.1:27017] on first connect
    at Pool.<anonymous> (H:\Loupning\Programming\Arkium\node_modules\mongodb-core\lib\topologies\server.js:326:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (H:\Loupning\Programming\Arkium\node_modules\mongodb-core\lib\connection\pool.js:270:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (H:\Loupning\Programming\Arkium\node_modules\mongodb-core\lib\connection\connection.js:175:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

I didn't change anything, database is giving me problem it seems.

**Comment by rm2kdev** [comment]
Its just failing to connect to your database, please double check your mongodb settings and ensure the database is running at 127.0.0.1:27017

**Comment by Yushe** [comment]
I get this error a few seconds after it says the server is running.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connection closed
    at null.<anonymous> (c:\Users\Yushe\WebstormProjects\mmorpg\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:601:24)
    at emit (events.js:92:17)
    at null.<anonymous> (c:\Users\Yushe\WebstormProjects\mmorpg\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:165:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (c:\Users\Yushe\WebstormProjects\mmorpg\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:549:12)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:465:12)
```
